
sudo: required
language: node_js
node_js:
  - '10'
env:
  global:
before_install:
  - npm install 
script:
  - npx vuepress build .
deploy:
  provider: pages
  target-branch: master
  skip-cleanup: true
  local-dir: docs/.vuepress/dist
  repo: qiphon/yd-learn
  github-token: $REPO_TOKEN
  keep-history: true
  on:
    branch: master